apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: edy005dtc-python 
  janus-idp.io/tekton: edy005dtc-python
  backstage.io/kubernetes-id: edy005dtc-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: edy005dtc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml