apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: edy005dtc-python-gitops
  description: This is GitOps manifest for edy005dtc-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=edy005dtc-python
    backstage.io/kubernetes-id: edy005dtc-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: edy005dtc-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:edy005dtc-python
